apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-reactive-caller
  namespace: ropt
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ropt-reactive-caller
  template:
    metadata:
      name: ropt-reactive-caller-pod
      labels:
        app: ropt-reactive-caller
        team: vsp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ropt-reactive-caller-container
          image: vladstep/ropt-reactive-caller:{{ropt-image-tag}}
          imagePullPolicy: Always
          ports:
            - name: caller-r-port
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-reactive-caller-cip-svc
  namespace: ropt
  labels:
    app: ropt-reactive-caller-cip
    vsp.monitor: caller-react-service
spec:
  selector:
    app: ropt-reactive-caller
  type: ClusterIP
  ports:
    - name: caller-r-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-reactive-caller-svc
  namespace: ropt
  labels:
    app: ropt-reactive-caller
spec:
  selector:
    app: ropt-reactive-caller
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8080