---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-reactive-caller
  namespace: ropt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ropt-reactive-caller
  template:
    metadata:
      name: ropt-reactive-caller-pod
      labels:
        app: ropt-reactive-caller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ropt-reactive-caller-container
          image: vladstep/ropt-reactive-caller:{{ropt-image-tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 1
              successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 1
              successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-reactive-caller-cip-svc
  namespace: ropt
  labels:
    app: ropt-reactive-caller
spec:
  selector:
    app: ropt-reactive-caller
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-reactive-caller-svc
  namespace: ropt
  labels:
    app: ropt-reactive-caller
spec:
  selector:
    app: ropt-reactive-caller
  type: LoadBalancer
  ports:
    - port: 8084
      targetPort: 8080