FROM adoptopenjdk/openjdk11:jre-11.0.10_9-alpine

COPY reactive-optimization-test/ropt-reactive-caller/target/ropt-reactive-caller.jar /ropt-reactive-caller.jar

CMD ["java", "-jar", "/ropt-reactive-caller.jar"]
