apiVersion: v1
kind: Service
metadata:
  name: pg-db-svc-ext
spec:
  ports:
    - name: pg-db-svc-ext-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
selector:
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg-db-svc-ext
subsets:
  - addresses:
      - ip: 192.168.7.101
    ports:
      - port: 5432
        name: pg-db-svc-ext-port
