apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-localizer
  namespace: ropt
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: r-localizer
  template:
    metadata:
      name: r-localizer-pod
      labels:
        app: r-localizer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: r-localizer-container
          image: charlie.lan/ropt/ropt-localizer-reactive:latest
          imagePullPolicy: Always
          ports:
            - name: r-localizer-p
              containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /availability/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /availability/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          env:
            - name: PG_UN
              valueFrom:
                secretKeyRef:
                  name: pg-db-creds
                  key: un
            - name: PG_PS
              valueFrom:
                secretKeyRef:
                  name: pg-db-creds
                  key: ps
            - name: POSTGRES_SVC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pg-service
            - name: PG_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pg-max-pool-size
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - r-localizer
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - sierra