apiVersion: v1
kind: Service
metadata:
  name: pg-db-svc-ext
spec:
  type: ClusterIP
  ports:
    - name: training-port
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg-db-svc-ext
subsets:
  - addresses:
      - ip: 192.168.7.101
    ports:
      - port: 5432