apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-receiver
  namespace: ropt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ropt-receiver
  template:
    metadata:
      name: ropt-receiver-pod
      labels:
        app: ropt-receiver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ropt-receiver-container
          image: vladstep/ropt-receiver:latest
          imagePullPolicy: Always
          ports:
            - name: receiver-port
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"