---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ropt-receiver
  template:
    metadata:
      name: ropt-receiver-pod
      labels:
        app: ropt-receiver
    spec:
      containers:
        - name: ropt-receiver-container
          image: vladstep/ropt-receiver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-receiver-cip-svc
  labels:
    app: ropt-receiver
spec:
  selector:
    app: ropt-receiver
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-receiver-svc
  labels:
    app: ropt-receiver
spec:
  selector:
    app: ropt-receiver
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 8080