apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: vsp-elasticsearch
  namespace: elastic-system
spec:
  version: 7.13.1
  nodeSets:
  - name: default
    count: 1
    config:
      # node.roles: ["master"]
      # node.remote_cluster_client: false  
      node.store.allow_mmap: false
  # - name: ingest-data
  #   count: 1
  #   config:
  #     node.roles: ["data", "ingest"]
  #     node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: vsp-kibana
  namespace: elastic-system
spec:
  version: 7.13.1
  count: 1
  elasticsearchRef:
    name: vsp-elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    # tls:
    #   selfSignedCertificate:
    #     subjectAltNames:
    #     - ip: 192.168.7.101
    #     - dns: localhost
    tls:
      selfSignedCertificate:
        disabled: true