---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-caller
  namespace: ropt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ropt-caller
  template:
    metadata:
      name: ropt-caller-pod
      labels:
        app: ropt-caller
        team: vsp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ropt-caller-container
          image: vladstep/ropt-caller:{{ropt-image-tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#              initialDelaySeconds: 30
#              periodSeconds: 10
#              timeoutSeconds: 2
#              failureThreshold: 1
#              successThreshold: 1
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#              initialDelaySeconds: 30
#              periodSeconds: 10
#              timeoutSeconds: 2
#              failureThreshold: 1
#              successThreshold: 1
#insecure.skip.tls.verify: true
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-caller-cip-svc
  namespace: ropt
  labels:
    app: ropt-caller
    team: vsp
spec:
  selector:
    app: ropt-caller
  type: ClusterIP
  ports:
    - name: ropt-caller-cip-svc-port
      port: 8080
      targetPort: ropt-caller-cip-svc-port
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-caller-svc
  namespace: ropt
  labels:
    app: ropt-caller
spec:
  selector:
    app: ropt-caller
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080