apiVersion: v1
kind: Service
metadata:
  name: logstash-svc-ext
  namespace: ropt
spec:
  ports:
    - name: logstash-svc-ext-port
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 0
selector:
---
apiVersion: v1
kind: Endpoints
metadata:
  name: logstash-svc-ext
  namespace: ropt
subsets:
  - addresses:
      - ip: 192.168.7.101
    ports:
      - port: 5000
        name: logstash-svc-ext-port
