apiVersion: v1
kind: Service
metadata:
  name: grafana-np
spec:
  type: NodePort
  ports:
    - name: grafana-port
      port: 3000
      nodePort: 30300
      protocol: TCP
      targetPort: grafana-port
  selector:
    app.kubernetes.io/instance: prom-stack
    app.kubernetes.io/name: grafana