apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ropt-caller-pod-monitor
  labels:
    team: vsp
spec:
  selector:
    matchLabels:
      app: ropt-caller
  namespaceSelector:
    matchNames:
      - ropt
  podMetricsEndpoints:
    - port: caller-port
      path: '/actuator/prometheus'
      interval: 10s