---
apiVersion: v1
kind: Service
metadata:
  name: ropt-r-caller-svc
  namespace: ropt
  labels:
    app: ropt-r-caller-svc
spec:
  selector:
    app: ropt-r-caller
  type: ClusterIP
  ports:
    - name: ropt-r-caller-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-receiver-svc
  namespace: ropt
  labels:
    app: ropt-receiver-svc
spec:
  selector:
    app: ropt-receiver
  type: ClusterIP
  ports:
    - name: ropt-receiver-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-r-receiver-svc
  namespace: ropt
  labels:
    app: ropt-r-receiver-svc
spec:
  selector:
    app: ropt-r-receiver
  type: ClusterIP
  ports:
    - name: ropt-receiver-r-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-localizer-svc
  namespace: ropt
  labels:
    app: ropt-localizer-svc
spec:
  selector:
    app: ropt-localizer
  type: ClusterIP
  ports:
    - name: ropt-localizer-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-r-localizer-svc
  namespace: ropt
  labels:
    app: ropt-r-localizer
spec:
  selector:
    app: ropt-r-localizer
  type: ClusterIP
  ports:
    - name: ropt-r-localizer-port
      port: 8080
      targetPort: 8080