apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-receiver
  namespace: ropt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: r-receiver
  template:
    metadata:
      name: r-receiver-pod
      labels:
        app: r-receiver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: r-receiver-container
          image: charlie.lan/ropt/ropt-receiver-reactive:latest
          imagePullPolicy: Always
          ports:
            - name: receiver-r-p
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          env:
            - name: PG_UN
              valueFrom:
                secretKeyRef:
                  name: pg-db-creds
                  key: un
            - name: PG_PS
              valueFrom:
                secretKeyRef:
                  name: pg-db-creds
                  key: ps
            - name: POSTGRES_SVC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pg-service
            - name: PG_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pg-max-pool-size
            - name: LCL_R_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: localizer-r-uri