apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropt-receiver-reactive
  namespace: ropt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ropt-receiver-reactive
  template:
    metadata:
      name: ropt-receiver-reactive-pod
      labels:
        app: ropt-receiver-reactive
        team: vsp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ropt-receiver-reactive-container
          image: vladstep/ropt-receiver-reactive:{{ropt-image-tag}}
          imagePullPolicy: Always
          ports:
            - name: receiver-r-port
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-receiver-reactive-cip-svc
  namespace: ropt
  labels:
    app: ropt-receiver-reactive-cip
    vsp.monitor: receiver-react-service
spec:
  selector:
    app: ropt-receiver-reactive
  type: ClusterIP
  ports:
    - name: receiver-r-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ropt-receiver-reactive-svc
  namespace: ropt
  labels:
    app: ropt-receiver-reactive
spec:
  selector:
    app: ropt-receiver-reactive
  type: LoadBalancer
  ports:
    - port: 8084
      targetPort: 8080