FROM adoptopenjdk/openjdk11:jre-11.0.10_9-alpine

COPY reactive-optimization-test/ropt-receiver-reactive/target/ropt-receiver-reactive.jar /ropt-receiver-reactive.jar

CMD ["java", "-jar", "/ropt-receiver-reactive.jar"]
